-- Update Faculty Emails and Offices
-- Generated from comprehensive-people-data.json

UPDATE faculties SET email = 'landeregg@ucsb.edu', phone = '805.893.2974', updated_at = datetime('now') WHERE full_name = 'Leander Anderegg';
UPDATE faculties SET email = 'briggs@lifesci.ucsb.edu', office = '2112 Noble Hall', phone = '805.893.2199', updated_at = datetime('now') WHERE full_name = 'Cherie Briggs';
UPDATE faculties SET email = 'deron.burkepile@lifesci.ucsb.edu', office = '4312 Marine Science Institute', phone = '805.893.3067', updated_at = datetime('now') WHERE full_name = 'Deron Burkepile';
UPDATE faculties SET email = 'dantonio@es.ucsb.edu', office = '4002 Bren Hall', phone = '805.893.2796', updated_at = datetime('now') WHERE full_name = 'Carla D''Antonio';
UPDATE faculties SET email = 'even@lifesci.ucsb.edu', office = '4322 Life Sciences Building', phone = '805.893.2904', updated_at = datetime('now') WHERE full_name = 'Thomas Even';
UPDATE faculties SET email = 'hefroehlich@ucsb.edu', office = '4007 Bren Hall', phone = '805.893.7016', updated_at = datetime('now') WHERE full_name = 'Halley Froehlich';
UPDATE faculties SET email = 'hodges@lifesci.ucsb.edu', office = '4105 Life Sciences Building', phone = '805.893.7813', updated_at = datetime('now') WHERE full_name = 'Scott Hodges';
UPDATE faculties SET email = 'hofmann@ucsb.edu', office = '4310 Marine Science Institute', phone = '805.893.6175', updated_at = datetime('now') WHERE full_name = 'Gretchen Hofmann';
UPDATE faculties SET email = 'iglesias@lifesci.ucsb.edu', office = '3151 Marine Biotech', phone = '805.893.4680', updated_at = datetime('now') WHERE full_name = 'Débora Iglesias-Rodriguez';
UPDATE faculties SET email = 'ajames@ucsb.edu', phone = '805.893.2974', updated_at = datetime('now') WHERE full_name = 'Anna James';
UPDATE faculties SET email = 'kuris@lifesci.ucsb.edu', office = '2002 Marine Biotech', phone = '805.893.3998', updated_at = datetime('now') WHERE full_name = 'Armand Kuris';
UPDATE faculties SET email = 'jlatto@ucsb.edu', office = '4324 Life Sciences Building', phone = '805.893.5399', updated_at = datetime('now') WHERE full_name = 'John Latto';
UPDATE faculties SET email = 'sally@eri.ucsb.edu', office = '4308 Marine Science Institute', phone = '805.893.3951', updated_at = datetime('now') WHERE full_name = 'Sally MacIntyre';
UPDATE faculties SET email = 'jesusgm@ucsb.edu', phone = '805.893.2974', updated_at = datetime('now') WHERE full_name = 'Jesús Martínez-Gómez';
UPDATE faculties SET email = 'sjmazer@ucsb.edu', office = '4119 Life Sciences Building', phone = '805.893.8011', updated_at = datetime('now') WHERE full_name = 'Susan J. Mazer';
UPDATE faculties SET email = 'dmccauley@ucsb.edu', office = '2314 Marine Science Institute', phone = '805.893.2170', updated_at = datetime('now') WHERE full_name = 'Douglas McCauley';
UPDATE faculties SET email = 'oakley@ucsb.edu', office = '4101 Life Sciences Building', phone = '805.893.4715', updated_at = datetime('now') WHERE full_name = 'Todd Oakley';
UPDATE faculties SET email = 'ryoko.oono@lifesci.ucsb.edu', office = '1116 Noble Hall', phone = '805.893.5064', updated_at = datetime('now') WHERE full_name = 'Ryoko Oono';
UPDATE faculties SET email = 'sproul@ucsb.edu', office = '4109 Life Sciences Building', phone = '805.893.2974', updated_at = datetime('now') WHERE full_name = 'Stephen Proulx';
UPDATE faculties SET email = 'joel.rothman@lifesci.ucsb.edu', office = '3137 Bio II', phone = '805.893.7885', updated_at = datetime('now') WHERE full_name = 'Joel Rothman';
UPDATE faculties SET email = 'asantoro@ucsb.edu', office = '2155 Marine Biotech Lab', phone = '805.893.5318', updated_at = datetime('now') WHERE full_name = 'Alyson Santoro';
UPDATE faculties SET email = 'schimel@lifesci.ucsb.edu', office = '1108 Noble Hall', phone = '805.893.7688', updated_at = datetime('now') WHERE full_name = 'Joshua Schimel';
UPDATE faculties SET email = 'jsharbro@ucsb.edu', office = '1123 Biological Sciences 2', phone = '805-893-4432', updated_at = datetime('now') WHERE full_name = 'Joel Sharbrough';
UPDATE faculties SET email = 'jshay@ucsb.edu', office = '4320 Life Sciences Building', phone = '805.893.2974', updated_at = datetime('now') WHERE full_name = 'Jackie Shay';
UPDATE faculties SET email = 'sweet@lifesci.ucsb.edu', office = '1124 Noble Hall', phone = '805.893.3730', updated_at = datetime('now') WHERE full_name = 'Samuel Sweet';
UPDATE faculties SET email = 'athellman@ucsb.edu', office = 'Noble Hall 1112', phone = '805.893.2974', updated_at = datetime('now') WHERE full_name = 'Audrey Thellman';
UPDATE faculties SET email = 'athurber@ucsb.edu', office = 'Noble Hall 2136', phone = '805.893.2974', updated_at = datetime('now') WHERE full_name = 'Andrew Thurber';
UPDATE faculties SET email = 'tturner@lifesci.ucsb.edu', office = '4103 Life Sciences', phone = '805.893.3798', updated_at = datetime('now') WHERE full_name = 'Thomas Turner';
UPDATE faculties SET email = 'rvegathurber@ucsb.edu', office = 'MSRB 4326', phone = '805.893.xxxx', updated_at = datetime('now') WHERE full_name = 'Rebecca Vega Thurber';
UPDATE faculties SET email = 'elizabeth.wilbanks@lifesci.ucsb.edu', office = '2128 Noble Hall', phone = '805.893.2974', updated_at = datetime('now') WHERE full_name = 'Lizzy Wilbanks';
UPDATE faculties SET email = 'soojinyi@ucsb.edu', office = '4107 Life Science Building', phone = '805.893.2974', updated_at = datetime('now') WHERE full_name = 'Soojin Yi';
UPDATE faculties SET email = 'hillary.young@lifesci.ucsb.edu', office = '2116 Noble Hall', phone = '805.893.4681', updated_at = datetime('now') WHERE full_name = 'Hillary Young';
UPDATE faculties SET email = 'yongzhou@ucsb.edu', office = 'Bio II Room 1121', phone = '805.893.2974', updated_at = datetime('now') WHERE full_name = 'Yong Zhou';
UPDATE faculties SET email = 'ivia@ucsb.edu', phone = '805.893.2974', updated_at = datetime('now') WHERE full_name = 'Ivia Closset';
UPDATE faculties SET email = 'damuth@lifesci.ucsb.edu', office = '4107 Life Sciences', phone = '805.729.4393', updated_at = datetime('now') WHERE full_name = 'John Damuth';
UPDATE faculties SET email = 'christopher.evelyn@lifesci.ucsb.edu', phone = '805.893.2974', updated_at = datetime('now') WHERE full_name = 'Christopher Evelyn';
UPDATE faculties SET email = 'james.gately@lifesci.ucsb.edu', updated_at = datetime('now') WHERE full_name = 'James Gately';
UPDATE faculties SET email = 'ferdinand.pfab@gmail.com', office = '2003 Noble Hall', phone = '805.893.2974', updated_at = datetime('now') WHERE full_name = 'Ferdinand Pfab';
UPDATE staff_members SET email = 'eambrocio@lifesci.ucsb.edu', office = 'LSB 3320', phone = '805-893-4622', updated_at = datetime('now') WHERE full_name = 'Evelin Ambrocio-Silva';
UPDATE staff_members SET email = 'pdiaz@lifesci.ucsb.edu', office = 'Bio Receiving (Building 569) 1101', phone = '(805) 893-3234', updated_at = datetime('now') WHERE full_name = 'Paul Diaz';
UPDATE staff_members SET email = 'cdrake@ucsb.edu', office = '1118 BSIF', phone = '805.893.3357', updated_at = datetime('now') WHERE full_name = 'Catherine Drake';
UPDATE staff_members SET email = 'sayward.halling@lifesci.ucsb.edu', office = '1118 Biological Sciences Instructional Facility', phone = '805.893.3357', updated_at = datetime('now') WHERE full_name = 'Sayward Halling';
UPDATE staff_members SET email = 'cameron.hannah-bick@lifesci.ucsb.edu', office = '540 Greenhouse', phone = '805.893.2867', updated_at = datetime('now') WHERE full_name = 'Cameron Hannah-Bick';
UPDATE staff_members SET email = 'andrea.jorgensen@lifesci.ucsb.edu', office = '4306 Life Sciences Building', phone = '805.893.2974', updated_at = datetime('now') WHERE full_name = 'Andrea Jorgensen';
UPDATE staff_members SET email = 'ryan.langlo@lifesci.ucsb.edu', office = '1250A Bio Shop', phone = '(805) 893-7286', updated_at = datetime('now') WHERE full_name = 'Ryan Langlo';
UPDATE staff_members SET email = 'info@eemb.ucsb.edu', office = 'BSIF 2219', updated_at = datetime('now') WHERE full_name = 'Saru Lantier';
UPDATE staff_members SET email = 'haleymartin@ucsb.edu', office = '4308 Life Sciences Building', phone = '805-893-2427', updated_at = datetime('now') WHERE full_name = 'Haley Martin';
UPDATE staff_members SET email = 'alicetn@ucsb.edu', office = '4326 Life Sciences Building', phone = '805.893.2679', updated_at = datetime('now') WHERE full_name = 'Alice Nguyen';
UPDATE staff_members SET email = 'michael.oconnell@lifesci.ucsb.edu', office = '1007 Marine Biotech', phone = '805.893.7181', updated_at = datetime('now') WHERE full_name = 'Michael (Mickey) O''Connell';
UPDATE staff_members SET email = 'christian.orsini@lifesci.ucsb.edu', office = '102 Building 465', phone = '805.893.2873', updated_at = datetime('now') WHERE full_name = 'Christian Orsini';
UPDATE staff_members SET email = 'info@eemb.ucsb.edu', office = '1118 Biological Sciences Instructional Facility', phone = '805.893.3357', updated_at = datetime('now') WHERE full_name = 'Oscar Perez';
UPDATE staff_members SET email = 'dcperez@ucsb.edu', office = '4316 Life Sciences Building', phone = '805.893.3775', updated_at = datetime('now') WHERE full_name = 'Danielle Perez';
UPDATE staff_members SET email = 'pierre@lifesci.ucsb.edu', phone = '+1 805-893-2873', updated_at = datetime('now') WHERE full_name = 'Christoph Pierre';
UPDATE staff_members SET email = 'rosavasquez@ucsb.edu', office = 'LSB 4310', phone = '805-893-7394', updated_at = datetime('now') WHERE full_name = 'Rosa Vasquez';
UPDATE staff_members SET email = 'info@eemb.ucsb.edu', office = '1255 Bio Shop', phone = '805.893.2974', updated_at = datetime('now') WHERE full_name = 'Patrick White';
UPDATE staff_members SET email = 'ewilkie@lifesci.ucsb.edu', office = '3318 Life Sciences Building', phone = '805.893.2974', updated_at = datetime('now') WHERE full_name = 'Ellery Wilkie';
UPDATE staff_members SET email = 'mengshuye@ucsb.edu', office = '4310 Life Sciences Building', phone = '805-893-3043', updated_at = datetime('now') WHERE full_name = 'Mengshu Ye';